dl_community_forum_homepage:
    path:     /forum
    defaults: { _controller: DlCommunityForumBundle:Default:index }

dl_community_forum_Subjet:
    path:     /subject/{idCate}
    defaults: { _controller: DlCommunityForumBundle:Default:sujet }

dl_community_forum_message:
    path:     /message
    defaults: { _controller: DlCommunityForumBundle:Default:message }
