dl_community_forum:
    resource: "@DlCommunityForumBundle/Resources/config/routing.yml"
    prefix:   /

dl_community_conection_inscription:
    resource: "@DlCommunityConectionInscriptionBundle/Resources/config/routing.yml"
    prefix:   /

dl_community_core:
    resource: "@DlCommunityCoreBundle/Resources/config/routing.yml"
    prefix:   /
