
dl_community_admin:
    resource: "@DlCommunityAdminBundle/Resources/config/routing.yml"
    prefix:   /

dl_community_conection_inscription:
    resource: "@DlCommunityConectionInscriptionBundle/Resources/config/routing.yml"
    prefix:   /
    
dl_community_inscription:
    path: /inscription
    defaults:
        _controller: DlCommunityConectionInscriptionBundle:Inscription:inscription


dl_community_core:
    resource: "@DlCommunityCoreBundle/Resources/config/routing.yml"
    prefix:   /
    
login:
    path: /login
    defaults:
        _controller: DlCommunityConectionInscriptionBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
