<?php

namespace DlCommunity\ConectionInscriptionBundle\Repository;

/**
 * inverceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class inverceRepository extends \Doctrine\ORM\EntityRepository
{
}
