<?php

namespace DlCommunity\ConectionInscriptionBundle\Repository;

/**
 * Test2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Test2Repository extends \Doctrine\ORM\EntityRepository
{
}
