<?php

namespace DlCommunity\CoreBundle\Repository;

/**
 * categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAll()
    {

        return $this -> getEntityManager ()
            ->createQuery (
             'SELECT * FROM DlCommunity\CoreBundle\Entity\Category *'
            ) 
            -> getResult()
            ;

    }

}
 