<?php

namespace DlCommunity\CoreBundle\Repository;

/**
 * forum_messageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Forum_messageRepository extends \Doctrine\ORM\EntityRepository
{
}
