<?php

namespace DlCommunity\CoreBundle\Repository;

/**
 * informationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{
}
