<?php

namespace DlCommunity\CoreBundle\Repository;

/**
 * information_statusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Information_statusRepository extends \Doctrine\ORM\EntityRepository
{
}
