<?php

namespace DlCommunity\CoreBundle\Repository;

/**
 * informationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository {

    private $lastName = 'MAMY';
    private $firstName = 'pierre';
    private $trainingStart = 'pierre';
    
    

    public function getInfoWithInfoStatus() {

        $qb = $this->getQueryBuilderInfoStatus();

        return $qb->getQuery()->getResult();
    }

    

    public function isINinformation(\DlCommunity\CoreBundle\Entity\Information $information) {
        $lastMane = $information->getLastName();
        $firstName = $information->getFirstName();
        $trainingStart = $information->getTrainingStart();

        $qb = $this->getQueryBuilderInfoStatus();
        $qb->where('info.lastName = :lastName')->setParameter('lastName', $lastMane)
           ->andWhere('info.firstName = :firstName')->setParameter('firstName', $firstName)
           ->andWhere('info.trainingStart = :trainingStart')->setParameter('trainingStart', $trainingStart);

        return $qb->getQuery()->getResult();
    }


    
    
    private function getQueryBuilderInfoStatus() {

        $qb = $this
                ->createQueryBuilder('info')
                ->innerJoin('info.information_status', 'statu')
                ->addSelect('statu');
        
        return $qb;
    }
}
