<?php

namespace DlCommunity\CoreBundle\Repository;

/**
 * sub_categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sub_categoryRepository extends \Doctrine\ORM\EntityRepository
{
}
