<?php

namespace DlCommunity\CoreBundle\Repository;

/**
 * subjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends \Doctrine\ORM\EntityRepository
{
}
