<?php

namespace DlCommunity\CoreBundle\Repository;

/**
 * user_categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_categoryRepository extends \Doctrine\ORM\EntityRepository
{
}
