<?php

namespace DlCommunity\CoreBundle\Repository;

/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository {

    public function getUser_information() {

        $qb = $this->getQueryBuilderInfoStatus();

        return $qb->getQuery()->getResult();
    }

    public function isINinformation(\DlCommunity\CoreBundle\Entity\Information $information) {
        $lastMane = $information->getLastName();
        $firstName = $information->getFirstName();
        $trainingStart = $information->getTrainingStart();

        $qb = $this->getQueryBuilderInfoStatus();
        $qb->where('info.lastName = :lastName')->setParameter('lastName', $lastMane)
                ->andWhere('info.firstName = :firstName')->setParameter('firstName', $firstName)
                ->andWhere('info.trainingStart = :trainingStart')->setParameter('trainingStart', $trainingStart);

        return $qb->getQuery()->getResult();
    }

    public function myFindAllDQL() {
        $query = $this->getEntityManager()->createQuery('SELECT a FROM DlCommunityCoreBundle:User a');
        $results = $query->getResult();

        return $results;
    }

    private function getQueryBuilderInfoStatus() {

        $qb = $this
                ->createQueryBuilder('user')
                ->innerJoin('user.user_type', 'user_type')
                ->addSelect('user_type')
                ->innerJoin('user.information', 'information')
                ->addSelect('information')
                ->innerJoin('information.information_status', 'statu')
                ->addSelect('statu')
                ->innerJoin('user.validation_type', 'validation_type')
                ->addSelect('validation_type')
                ->innerJoin('user.picture', 'picture')
                ->addSelect('picture');

        return $qb;
    }

    public function isUser() {
        
    }

}
