<?php

namespace DlCommunity\CoreBundle\Repository;

/**
 * waiting_listRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Validation_typeRepository extends \Doctrine\ORM\EntityRepository
{
}
